In [ ]:
import numpy as np
import sklearn as sk
from sklearn.model_selection import train_test_split

TO DO: import load_wine from sklearn.datasets
 Then, create an instance __dataset__ by calling load_wine()

In [ ]:
from sklearn.datasets import load_wine
wine_dataset = load_wine()

TO DO: Display dataset.keys() and the elements of dataset.

In [ ]:
wine_dataset.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])

In [ ]:
print(wine_dataset['DESCR'])

.. _wine_dataset:

Wine recognition dataset
------------------------

**Data Set Characteristics:**

    :Number of Instances: 178 (50 in each of three classes)
    :Number of Attributes: 13 numeric, predictive attributes and the class
    :Attribute Information:
 		- Alcohol
 		- Malic acid
 		- Ash
		- Alcalinity of ash  
 		- Magnesium
		- Total phenols
 		- Flavanoids
 		- Nonflavanoid phenols
 		- Proanthocyanins
		- Color intensity
 		- Hue
 		- OD280/OD315 of diluted wines
 		- Proline

    - class:
            - class_0
            - class_1
            - class_2
		
    :Summary Statistics:
    
    ============================= ==== ===== ======= =====
                                   Min   Max   Mean     SD
    ============================= ==== ===== ======= =====
    Alcohol:                      11.0  14.8    13.0   0.8
    Malic Acid:                   0.74  5.80    2.34  1.12
    Ash:                          1.36  3.23    2.36  0.27
    Alcalinity of Ash:            1

In [ ]:
print(wine_dataset['feature_names'])

['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']


In [ ]:
print(wine_dataset['data'])

[[1.423e+01 1.710e+00 2.430e+00 ... 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 ... 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 ... 1.030e+00 3.170e+00 1.185e+03]
 ...
 [1.327e+01 4.280e+00 2.260e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [1.317e+01 2.590e+00 2.370e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [1.413e+01 4.100e+00 2.740e+00 ... 6.100e-01 1.600e+00 5.600e+02]]


In [ ]:
print(wine_dataset['target_names'])

['class_0' 'class_1' 'class_2']


In [ ]:
print(wine_dataset['target'])

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


TO DO: Split dataset into train and test sets, and print the shape of X_train, y_train, X_test and y_test

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(wine_dataset['data'],wine_dataset['target'],random_state=0)


print("X_train.shape =",X_train.shape)
print("y_train.shape =",y_train.shape)
print("X_test.shape =", X_test.shape)
print("y_test.shape =", y_test.shape)

X_train.shape = (133, 13)
y_train.shape = (133,)
X_test.shape = (45, 13)
y_test.shape = (45,)


TO DO: Build a classifier for the wine dataset using LogisicRegression, and print the accuracy on the training and test data.


In [ ]:
from sklearn.linear_model import LogisticRegression
logi_reg = LogisticRegression().fit(X_train,y_train)

print("train score = {}".format(logi_reg.score(X_train,y_train)))
print("train score = {}".format(logi_reg.score(X_test,y_test)))

train score = 0.9924812030075187
train score = 0.9333333333333333


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


TO DO: Save the weight matrix and bias vector of the LogisticRegression instance as W_lr and b_lr. Then, print them.

In [ ]:
W_lr = logi_reg.coef_
b_lr = logi_reg.intercept_

print("W_lr = {}".format(W_lr))
print("b_lr = {}".format(b_lr))

W_lr = [[-1.32186429e-01  3.23965050e-01  1.84092284e-01 -2.58932260e-01
  -3.55944236e-02  2.38697315e-01  5.82114322e-01 -2.22946486e-02
   9.92276027e-02  1.09948852e-01 -1.73973402e-02  4.10341111e-01
   8.36031752e-03]
 [ 5.99095455e-01 -7.17070268e-01 -2.00230225e-01  2.11071050e-01
  -1.04352065e-02  2.06746427e-01  3.95799510e-01  1.36191938e-02
   3.85959371e-01 -1.24982865e+00  2.65765529e-01  4.38399876e-01
  -8.01466640e-03]
 [-4.66909026e-01  3.93105218e-01  1.61379407e-02  4.78612099e-02
   4.60296301e-02 -4.45443742e-01 -9.77913832e-01  8.67545481e-03
  -4.85186974e-01  1.13987979e+00 -2.48368189e-01 -8.48740987e-01
  -3.45651121e-04]]
b_lr = [-0.04937168  0.10908187 -0.05971019]


TO DO: Build a classifier for the wine dataset using LinearSVC, and print the accuracy on the training and test data.

In [ ]:
from sklearn.svm import LinearSVC

LSVC = LinearSVC().fit(X_train,y_train)

print("train score = {}".format(LSVC.score(X_train,y_train)))
print("train score = {}".format(LSVC.score(X_test,y_test)))

train score = 0.8721804511278195
train score = 0.8444444444444444


/usr/local/lib/python3.6/dist-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


TO DO: Save the weight matrix and bias vector of the LinearSVC instance as W_svc and b_svc. Then, print them.

In [ ]:
W_svc = LSVC.coef_
b_svc = LSVC.intercept_

print("W_svc = {}".format(W_svc))
print("b_svc = {}".format(b_svc))

W_svc = [[-2.78505946e-02 -1.91070975e-03 -1.22114678e-03 -1.04789668e-01
  -8.03132258e-03  1.00121470e-02  3.07108803e-02 -4.00283863e-03
   7.74212278e-03 -1.96587023e-02 -8.44826133e-04  1.69274746e-02
   3.63798960e-03]
 [ 4.75354070e-02 -8.01138655e-02 -6.44210149e-03  3.20803143e-02
   5.05881918e-03  4.34221986e-02  7.64850225e-02  3.43489167e-05
   4.54401722e-02 -1.97821454e-01  3.18631918e-02  8.75456704e-02
  -3.52477041e-03]
 [-4.59003383e-02  8.09546947e-02  1.11734576e-03  8.17228541e-03
  -2.15596322e-03 -6.16656652e-02 -1.24727677e-01  2.64673991e-03
  -5.51896112e-02  2.15439050e-01 -3.29809926e-02 -1.15590564e-01
  -2.48005450e-04]]
b_svc = [-0.00404202  0.00918405 -0.00687752]


TO DO: Define a class __SimpleLinearClassifier__ composed of the following functions:

* __\_\_init\_\___(self, weight, bias) - takes a weight matrix and a bias vector as input and stores them in instance variables

* __predict(self, X)__ - takes an array of rank 2 as input, and returns the classification results as an array of rank 1

* __probability(self, X)__ - takes an array of rank 2 as input and returns the probabilities that each sample belongs to each class as an array of rank 2. (You need to implement the softmax function to convert logits into probabilities.)

* __score(self, X, y)__ - takes an input data (rank 2) and a target vector (rank 1) as input, and returns the accuracy as a scalar value.


The __SimpleLinearClassifier__ should work as the following examples.

In [ ]:
# Define SimpleLienarClassfier here.

class SimpleLinearClassifier:
  weight = [[]]
  bias = []

  def __init__(self,weight,bias):
    self.weight = weight
    self.bias = bias

  def predict(self, X):
    result = []
    for feature in X:
      y = np.sum((feature*self.weight),axis=1) + self.bias
      
      result.append(np.argmax(y))
      # result = np.append(result, np.argmax(y))
      
         
    return np.array(result) 

  def probability(self, X):
    result = []
    for feature in X:
      y = np.sum((feature*self.weight),axis=1) + self.bias
      y = ( np.exp(y)/ np.sum(np.exp(y)))
      result.append(y)

    
    return np.array(result)


  def score(self, X, y):
    return np.equal(self.predict(X),y).mean()
  
  
   

TO DO: Create a SimpleLinearClassfier instance simple_lr using W_lr and b_lr. Then, print the accuracy on the training and test data.<br>
(The accuracies should be the same as those of the LogisticRegression instance.)

In [ ]:
simple_lr = SimpleLinearClassifier(W_lr,b_lr)

print("train score = {}".format(simple_lr.score(X_train,y_train)))
print("test score = {}".format(simple_lr.score(X_test,y_test)))

train score = 0.9924812030075187
test score = 0.9333333333333333


TO DO: Display the results of simple_lr.predict(X_test) along with y_test.

In [ ]:
print("y_hat = {}".format(simple_lr.predict(X_test)))
print("y_test = {}".format(y_test))

y_hat = [0 2 1 0 1 1 0 2 1 1 2 2 0 1 2 1 0 0 2 0 1 0 1 1 1 1 1 1 1 2 0 0 1 0 0 0 2
 1 1 2 1 0 1 1 1]
y_test = [0 2 1 0 1 1 0 2 1 1 2 2 0 1 2 1 0 0 1 0 1 0 0 1 1 1 1 1 1 2 0 0 1 0 0 0 2
 1 1 2 0 0 1 1 1]


TO DO: Display the result of simple_lr.probability(X_test).
Then, check whether the sum of each row makes one.

In [ ]:
print("prob =", simple_lr.probability(X_test)) 
print("The sum of rows =", np.sum(simple_lr.probability(X_test), axis=1))

prob = [[9.91523974e-01 1.06809396e-03 7.40793157e-03]
 [3.77327532e-06 1.30747729e-07 9.99996096e-01]
 [3.44245206e-03 9.96346395e-01 2.11152743e-04]
 [9.84160185e-01 1.48380428e-03 1.43560112e-02]
 [3.47198262e-03 9.96246866e-01 2.81151540e-04]
 [3.24070085e-03 9.92522269e-01 4.23702975e-03]
 [9.98974254e-01 8.79461736e-05 9.37799443e-04]
 [9.33756528e-04 9.70685064e-05 9.98969175e-01]
 [7.45239054e-03 9.91861675e-01 6.85934882e-04]
 [1.77271256e-03 9.97704602e-01 5.22685383e-04]
 [8.96380394e-02 1.14086635e-02 8.98953297e-01]
 [2.34976560e-03 2.79276387e-02 9.69722596e-01]
 [9.99918361e-01 3.14178153e-07 8.13251425e-05]
 [1.98520006e-01 8.00879300e-01 6.00693636e-04]
 [3.52047348e-04 1.71638882e-05 9.99630789e-01]
 [2.14401123e-05 9.99974013e-01 4.54707456e-06]
 [9.88633382e-01 7.01422817e-04 1.06651955e-02]
 [9.99961126e-01 9.20343542e-10 3.88732006e-05]
 [8.16704638e-03 1.12844947e-01 8.78988007e-01]
 [9.99869347e-01 5.27342750e-05 7.79184901e-05]
 [1.18290976e-01 8.81018904e-01 6

TO DO: Print the accuracy on the training and test data.

In [ ]:
print("train score = {}".format(simple_lr.score(X_train,y_train)))
print("test score = {}".format(simple_lr.score(X_test,y_test)))

train score = 0.9924812030075187
test score = 0.9333333333333333


TO DO: Create a SimpleLinearClassfier instance simple_svc using W_svc and b_svc. Then, print the accuracy on the training and test data.<br>
(The accuracies should be the same as those of the LinearSVC instance.)

In [ ]:
simple_svc = SimpleLinearClassifier(W_svc,b_svc)

print("train score = {}".format(simple_svc.score(X_train,y_train)))
print("test score = {}".format(simple_svc.score(X_test,y_test)))

train score = 0.8721804511278195
test score = 0.8444444444444444


TO DO: Display the results of simple_svc.predict(X_test) along with y_test.

In [ ]:
print("y_hat = {}".format(simple_svc.predict(X_test)))
print("y_test = {}".format(y_test))

y_hat = [0 2 1 0 1 1 0 2 1 1 2 2 0 0 2 1 0 0 2 0 1 0 2 0 0 1 1 1 2 2 0 0 2 0 0 0 2
 1 1 2 0 0 1 1 1]
y_test = [0 2 1 0 1 1 0 2 1 1 2 2 0 1 2 1 0 0 1 0 1 0 0 1 1 1 1 1 1 2 0 0 1 0 0 0 2
 1 1 2 0 0 1 1 1]


TO DO: Display the result of simple_svc.probability(X_test).
Then, check whether the sum of each row makes one.

In [ ]:
print("prob =", simple_svc.probability(X_test)) 
print("The sum of rows =", np.sum(simple_svc.probability(X_test), axis=1))

prob = [[7.95384546e-01 2.65129991e-02 1.78102454e-01]
 [3.72910660e-02 4.33387062e-02 9.19370228e-01]
 [1.46002302e-01 5.67131077e-01 2.86866621e-01]
 [7.50929442e-01 2.61137011e-02 2.22956857e-01]
 [8.95246718e-02 6.25672365e-01 2.84802963e-01]
 [5.24009715e-02 6.18602995e-01 3.28996033e-01]
 [9.08125833e-01 7.82804204e-03 8.40461251e-02]
 [9.43398760e-02 8.21586412e-02 8.23501483e-01]
 [2.29346316e-01 4.37954610e-01 3.32699074e-01]
 [2.03159940e-01 4.88338235e-01 3.08501825e-01]
 [3.55296603e-01 7.30561936e-02 5.71647204e-01]
 [8.93792369e-02 1.95234440e-01 7.15386323e-01]
 [9.54512038e-01 1.38828054e-03 4.40996814e-02]
 [4.26005741e-01 2.85374051e-01 2.88620208e-01]
 [1.26634994e-01 4.36616611e-02 8.29703345e-01]
 [5.72768518e-02 7.94633189e-01 1.48089959e-01]
 [8.47458251e-01 1.60777912e-02 1.36463958e-01]
 [9.69942801e-01 2.25929293e-04 2.98312699e-02]
 [1.54762645e-01 2.58197891e-01 5.87039464e-01]
 [9.17109757e-01 6.32774179e-03 7.65625017e-02]
 [3.29909309e-01 3.43755278e-01 3

TO DO: Print the accuracy on the training and test data.

In [ ]:
print("train score = {}".format(simple_svc.score(X_train,y_train)))
print("test score = {}".format(simple_svc.score(X_test,y_test)))

train score = 0.8721804511278195
test score = 0.8444444444444444
