#Scientific Packages#
- 파이썬은 언어의 기능은 부족한 편이나, 부족한 점을 확장팩으로 해결한다. 
- 여러가지 패키지 중에 대표적으로 잘 사용되는 scientific packages 들이 있다. 

###1. numpy ###
- 파이썬의 list는 array와 동작이 유사하지만 list가 free container여서 되게 느린 데이터프레임이다. 
- numpy는 다차원의 array를 사용하며, 이 array는 대빵 빠르다. 

###2. scikit-learn###
- 머신러닝에 대한 패키지이다. 고전적인 ML이 많다. API가 하나로 통합되어서 인터페이스만 알면 여러가지 모듈을 쉽게 사용할 수 있다. 

###3. xgboost###
- 단순한 문제에 대해서 성능이 아주 좋다. 

###4. pydnn ###
###5. matplotlib###
- 데이터를 시작화 하는데 특화되어 있다. 자료를 분석할 때 시각화를 통해 자료를 이해하는 것은 매우 중요하다. 

###6. pandas###
- pandas는 데이터를 불러올 때 아주 유용하다. 예를 들어 excel이나 csv 파일을 읽고 쓸때 능하다. 

###(7. mglearn)###
- sk 기반으로 만들어진 교육용 패키지 이다. 

In [ ]:
#importing basic science packages 
import numpy as np
import sklearn as sk
import xgboost as xgb
import matplotlib.pyplot as plt 

! pip install mglearn
import mglearn 

# importing pytorch
import torch
import torchvision
import torch.nn as nn

# importing tensorflow 
import tensorflow as tf
from tensorflow import keras
# import tensorflow.contrib.slim as slim 


def typeNprint(source):
  print(type(source))
  # print(source)
  print(source.shape)
  print()

## Importing packages ## 
!주의! matplotlib은 그 자체로 import가 아니고 pyplot이라는 sub-category로 import를 해야한다. 

#Scikit-learn#
- sklearn은 머신러닝을 위한 다양한 패키지들이 많고, 일장 일단이 확실하다(데이터마다 특화가 되어있다). 

1. Classification
- k-NN, decision trees, random forests, MLP, SVM ... 
2. Regression
- linear, Ridge, Lasso, ElasticNet, SVR, ...
3. Clustering
- k-Means, spectral, ...
4. Dimensionality reduction
- PCA, LDA 


__그런데 scikit-learn을 사용하면 해당 방법들이 다 구현이 되어 있다. 또한 메뉴얼이 매우 잘 되어 있어서 스스로 학습하기에 좋다. __


In [ ]:
# Iris Dataset in scikit-learn 
from sklearn.datasets import load_iris 
iris_dataset = load_iris() 

print(type(iris_dataset))
print(type(iris_dataset.data))
print(iris_dataset.data.shape) # shape는 () 메소드 호출의 형태가 아니고 그냥 변수처럼 찍음 
#  numpy.ndarray 의 경우 shape으로 어떻게 생겼는지 확인할 수 있다. 



<class 'sklearn.utils.Bunch'>
<class 'numpy.ndarray'>
(150, 4)


# split training/test dataset
#- train_test_split
### 해당 함수는 진짜 매번쓴다 너무 많이 쓴다 
from sklearn.model_selection import train_test_split 

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(iris_dataset.data,
                                                    iris_dataset.target,
                                                    random_state = 0)

print("X_train type : ", type(X_train))
print("X_test type : ", type(X_test))
print("y_train type : ", type(y_train))
print("y_test type : ", type(y_test))

print()

print("X_train type : ",X_train.shape)
print("X_test type : ",X_test.shape)
print("y_train type : ",y_train.shape)
print("y_test type : ",y_test.shape)
# 보면 대략적으로 75:25 정도로 데이터가 나뉜다.
# feature samples 와 label (정답)이 제공된다. 
# random_state를 설정해서 데이터가 나뉘는 케이스를 고정해야한다.  

X_train type :  <class 'numpy.ndarray'>
X_test type :  <class 'numpy.ndarray'>
y_train type :  <class 'numpy.ndarray'>
y_test type :  <class 'numpy.ndarray'>

X_train type :  (112, 4)
X_test type :  (38, 4)
y_train type :  (112,)
y_test type :  (38,)


In [ ]:
#################################################################
#  자습 

from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 3)
knn.fit(X_train,y_train)

prediction = knn.predict(X_test)
print("정확도 = {:.4}".format(knn.score(X_test,y_test)))

#  자습 
#################################################################

정확도 = 0.9737


# Pandas 
- 데이터 분석을 위한 패키지 이다. 
1. 데이터를 수집
2. 엑셀로 특징별 기록
3. 엑셀에 있는 데이터를 파이썬에 불러온다.
- 해당 일련의 과정을 수행할때 pandas 패키지를 사용해서 파이썬에 쉽게 불러올 수 있다. 

-결국 모든 과정은 
1. 데이터를 수집하고
2. 해당 데이터들을 정리하고
3. 해당 데이터들을 호출해서
4. 시각화 혹은 목적에 맞게끔 재정리를 한다음
5. 넘파이로 변환하여 사용을 한다. 


In [ ]:
import numpy as np # 머신러닝을 사용할 때, 넘파이 배열로 학습을 하기 때문이다.
import pandas as pd 

# 예시코드 (수행 안됨.)
df = pd.read_csv(<filename>)

df['날짜'] # column '날짜' 열
df.iloc[2] # 2번째 열 

df.describe() # 데이터 상태를 확인하고 분석 

nparrya = df.to_numpy() # 데이터 프레임을 넘파이 배열로 전환 

SyntaxError: ignored

In [ ]:
import sklearn as sk
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train,y_train)

prediction = knn.predict(X_test)
print(type(prediction))
print(prediction.shape)
print(prediction)

# 넘파이 어레이 : Numpy Array
- 데이터 타입 = numpy.ndarray 
- n차원의 어레이 이며, 동일한 데이터 타입(파이썬의 list는 자율 형식임)을 구성하고 있다. 


In [ ]:
# creating n using array

# 방법 1) 가장 직관적인 방법, 파이썬의 List를 인자로 건네줌
a = np.array([1,2,3])

print(type(a))
print(a.shape)
print()

# np array도 인덱스로 접근하면 elements만 리턴이 됨 
print(a[0],a[1],a[2]) 
print(a)
print()

a[0] = 5
print(a)


b = np.array([[1,2,3],
              [4,5,6]])

print(type(b))
print(b.shape)
print()

print(b) # [[1 2 3]
         #  [4 5 6]]

print(b[0:1]) # [[1 2 3]]
print(b[0])   # [1 2 3]
print(b[:, 0:2])
print(b[:,1])


In [ ]:
# Creating Array 
print(type((2,3)))

# 0으로 채워서 만들기 
a = np.zeros((2,3)) # 내부에 튜플로 제공할 수 있움
print(a)
print()

# 1로 채워서 만들기
b = np.ones((3,3))
print(b)
print()

# 지정한 상수값으로 채워서 만들기
c = np.full((4,5), 16)
print(c)
print()

# 단위행렬 I 만들기 
d = np.eye(5) # 단위행렬은 사각이여서 value 하나를 받고 n*n 으로 만듬
print(d)
print()

# 아무 값이나 채워서 만들기 
e = np.random.random((2,2))
print(e)
print()

In [ ]:
# 슬라이싱!
# -> 해당 자료의 차원을 그대로 유지함
sourceList = [[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]]
a = np.array(sourceList)
print(a)
print()

b = a[0:2 , 1:3]
print(b)
print()


# 2차원에서 첫번째 친구가 row! 가로
row_r1 = a[1, :]
row_r2 = a[1:2, :] # slicing 

print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)
print()


# 2차원에서 두번째 친구가 column! 세로
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]

print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape)

In [ ]:
# Broadcasting 
# 더하거나 뺄때, 랭크가 다른 경우 진행이 되는 것
# 랭크가 작은 쪽을 확장하고, 그 후에 진행이 된다. 

x = np.array([[1,2,3],
              [4,5,6],
              [7,8,9],
              [10,11,12]])
v = np.array([1,0,1])
vt = np.array([[1],
               [0],
               [1]])
print(x.shape)
print(v.shape)
print(vt.shape)
print(vt.transpose()) # transpose() 는 rank가 2일때만 동작함요. 

print()

y = x + v
print(y.shape)
print(y)
print()

y2 = x * v 
print(y2.shape)
print(y2)
print()

y3 = x + vt
print(y3.shape)
print(y3)
print()

y4 = x * vt
print(y4.shape)
print(y4)
print()

In [ ]:
# reshape()
a = np.arange(0,20)
print(a.shape)
typeNprint(a)

# 인자를 -1 로 주면 파이썬이 나머지를 알아서 계산해! 라는 뜻임 
b = np.reshape(a, (2,-1))
print(b.shape)
typeNprint(b)

In [ ]:
# expand_dims() 
# 새로운 axis:축 을 받아서 확장함 
c = np.expand_dims(a, axis =0)

print(a.shape)
typeNprint(a)
print(c.shape)
typeNprint(c)

ct = np.expand_dims(a, axis=1)
print(ct.shape)
typeNprint(ct)

# AxisError: axis 2 is out of bounds for array of dimension 2
# ctt = np.expand_dims(a, axis=2)
# print(ctt.shape)
# typeNprint(ctt)

In [ ]:
print(c.shape)
f = np.squeeze(c)
print(f.shape)
typeNprint(f)

print(ct.shape)
ft = np.squeeze(ct)
print(ft.shape)
typeNprint(ft)

# squeeze 함수는 1차원인 축을 다 조짐 
# ex) shape => (1,2,1) => (2) 일케됨. 
# axis를 통해 조질 축을 지정할 수 있음 
setup = np.squeeze(c,axis=0)
# 대신 해당 차원이 1차원이여야한다. 

In [ ]:
# List comprehension
mul3_List = [k for k in range(1,101) if k%3==0]
print(mul3_List)

nums = [0, 1, 2, 3, 4]
even_squares = [x ** 2 for x in nums if x % 2 == 0]
print(even_squares)

In [ ]:
# enumerate() 함수
animals = ['cat', 'dog', 'monkey']
for idx, animal in enumerate(animals):
    print('{}: {}'.format(idx + 1, animal))

## dot product and matrix multiplication



In [ ]:
# 5) 만약 a가 N차원 배열이고 b가 2이상의 M차원 배열이라면, dot(a,b)는 a의 마지막 축과 b의 뒤에서 두번째 축과의 내적으로 계산된다
a = np.array([1, 0, 2, 1])
b = np.array([4, 1, 3, 2])
print("a = ", a)
print("b = ", b)             
print("np.dot(a, b) = ", np.dot(a, b))
print()



# 2) 만약 배열이 2차원보다 클 경우, 마지막 2개의 축으로 이루어진 행렬을 나머지 축에 따라 쌓아놓은 것이라고 생각한다.
a = np.array([[1, 0, 2],
              [0, 1, 4]])
b = np.array([[4, 1],
              [2, 2],
              [3, 5]])
print("a = ", a)
print("b = ", b)        
   
print("np.matmul(a, b) = ")
print(np.matmul(a, b))
print("np.matmul(b, a) = ")
print(np.matmul(b, a))

a =  [1 0 2 1]
b =  [4 1 3 2]
np.dot(a, b) =  12

a =  [[1 0 2]
 [0 1 4]]
b =  [[4 1]
 [2 2]
 [3 5]]
np.matmul(a, b) = 
[[10 11]
 [14 22]]
np.matmul(b, a) = 
[[ 4  1 12]
 [ 2  2 12]
 [ 3  5 26]]


#from Homework 1#


In [ ]:
A_data = np.random.random(100) * 100
typeNprint(A_data)

B_data = np.linspace(1,100)
typeNprint(B_data)

C_data = np.random.random((100,1)) * 100
typeNprint(C_data)

#  이걸로 (100,1)의 shape은 아마 못만드는 듯 
# reshape 해줘야 해용 
D_data = np.linspace((0,100),1,100)
typeNprint(D_data)
print(D_data[:10])

<class 'numpy.ndarray'>
(100,)

<class 'numpy.ndarray'>
(50,)

<class 'numpy.ndarray'>
(100, 1)

<class 'numpy.ndarray'>
(100, 2)

[[0.00000000e+00 1.00000000e+02]
 [1.01010101e-02 9.90000000e+01]
 [2.02020202e-02 9.80000000e+01]
 [3.03030303e-02 9.70000000e+01]
 [4.04040404e-02 9.60000000e+01]
 [5.05050505e-02 9.50000000e+01]
 [6.06060606e-02 9.40000000e+01]
 [7.07070707e-02 9.30000000e+01]
 [8.08080808e-02 9.20000000e+01]
 [9.09090909e-02 9.10000000e+01]]


In [ ]:
A_label = np.zeros(len(A_data))
print(A_label)

A1 = np.concatenate((A_data.reshape(-1,1), A_label.reshape(-1,1)), axis=1)
print(A1[:10])


A0 = np.concatenate((A_data.reshape(-1,1), A_label.reshape(-1,1)), axis=0)
print(A0[:10])



[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]
[[ 9.65808702  0.        ]
 [79.24610949  0.        ]
 [20.42634414  0.        ]
 [50.65677843  0.        ]
 [82.74220271  0.        ]
 [35.57471165  0.        ]
 [44.69229225  0.        ]
 [57.12488722  0.        ]
 [94.8021104   0.        ]
 [12.57512239  0.        ]]
[[ 9.65808702]
 [79.24610949]
 [20.42634414]
 [50.65677843]
 [82.74220271]
 [35.57471165]
 [44.69229225]
 [57.12488722]
 [94.8021104 ]
 [12.57512239]]


.axis

1차원 

- axis = 0 : 1차원 



2차원 
- axis = 0 : 2차원
- axis = 1 : 1차원


3차원
- axis = 0 : 3차원
- axis = 1 : 2차원
- axis = 2 : 1차원 

http://machinelearningkorea.com/2019/05/18/%ED%8C%8C%EC%9D%B4%EC%8D%AC-axis-%EC%9D%B4%ED%95%B4%ED%95%98%EA%B8%B0-%EC%B9%98%ED%8A%B8%EC%BD%94%EB%93%9C/

In [ ]:
ar = np.array([[1,2],[3,4],[5,6],[7,8]])
print(ar.shape)
print(ar)


ar0 = np.array_split(ar, 2, axis=0)
print(ar0)

ar1 = np.array_split(ar, 2, axis=1)
print(ar1)

(4, 2)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]
[array([[1],
       [3],
       [5],
       [7]]), array([[2],
       [4],
       [6],
       [8]])]


In [ ]:
array = np.random.randint(10, size=(5,3)) 
array

array([[7, 4, 9],
       [3, 4, 7],
       [4, 3, 3],
       [9, 2, 7],
       [9, 1, 1]])

In [ ]:
np.sum(array, axis = 0) # 5,3 에서 axis = 0 니까 5를 없에줌 

array([32, 14, 27])

In [ ]:
np.sum(array, axis = 1) # 5,3 에서 axis =1 이니까 3을 없에는 방향으로 슝슝 

array([20, 14, 10, 18, 11])

In [ ]:
array3 = np.random.randint(10, size=(5,3,2)) 
array3

array([[[6, 1],
        [4, 6],
        [0, 8]],

       [[7, 0],
        [3, 7],
        [8, 4]],

       [[1, 4],
        [9, 1],
        [4, 2]],

       [[1, 6],
        [9, 1],
        [2, 8]],

       [[1, 0],
        [2, 3],
        [3, 1]]])

In [ ]:
print(np.sum(array3, axis = 0))
print("")
print(np.sum(array3, axis = 0).shape)

[[16 11]
 [27 18]
 [17 23]]

(3, 2)


In [ ]:
print(np.sum(array3, axis = 1))
print("")
print(np.sum(array3, axis = 1).shape)

[[10 15]
 [18 11]
 [14  7]
 [12 15]
 [ 6  4]]

(5, 2)


In [ ]:
print(np.sum(array3, axis = 2))
print("")
print(np.sum(array3, axis = 2).shape)

[[ 7 10  8]
 [ 7 10 12]
 [ 5 10  6]
 [ 7 10 10]
 [ 1  5  4]]

(5, 3)
